version: '3.9'

services:
  mlp:
    image: drlight17/mta-log-parser:latest
    container_name: mta-log-parser
    command: /app/run.sh ${COMMAND}
    ports:
      - ${PORT}:${PORT}
    restart: always
    volumes:
      - ./.env:/app/.env
      - /tmp:/tmp
      - ${MAIL_LOG_PATH}:${MAIL_LOG_PATH}
    depends_on:
      - rethinkdb

  rethinkdb:
    image: rethinkdb:2.4
    container_name: rethinkdb
    ports:
      - ${RETHINK_EXP_GUI_PORT}:8080
    restart: always
    volumes:
      - ./:/data
